// <auto-generated />
namespace GowBoard.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class Home : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Home));
        
        string IMigrationMetadata.Id
        {
            get { return "202406290430272_[Home]"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
